### ISSUE TITLE
Interest in cfgv being typed?

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [asottile/cfgv#135]
I'm curious if cfgv being typed would be seen as a net benefit and thus if a PR that implements that would be considered. More than willing to attempt the PR if so. I'm partially motivated by interest in using it for a hobby project and wanted better typing support, but figured it isn't a bad quality-of-life idea in general.

**Comment by asottile** [comment]
please search the issue tracker for duplicates

**Comment by Sachaa-Thanasius** [comment]
I think the only possible duplicate is #75, which had a different use case entirely. I'm not referring to making the results of cfgv somehow refer to specific, generated, type-checked objects; I meant just adding some type annotations to the library, changing collections.namedtuples to typing.NamedTuples, maybe making a protocol for schema objects (with check, remove_default, add_default functions) that type-checkers will complain about if a custom schema object doesn't meet that criteria, that kind of thing.

Am I missing a more obvious duplicate about general improvement of the type annotations for the library?

**Comment by Sachaa-Thanasius** [comment]
Just following up to confirm, hope you don't mind, @asottile:

I couldn't find the duplicate you mentioned, as the only other seemingly related issue wasn't about adding/improving type annotations for the library, but about cfgv schemas being understood by mypy as class generators a la dataclasses. Am I missing something, or do you prefer this library entirely unannotated at this time anyhow?

Either way is fine, I'd just like to understand better what you want for cfgv. I thought a few type annotations would be a plus for maintenance and possible user experience, but I guess I was mistaken.

Anyway, I'll stop badgering you after this, just wanted to be perfectly clear on your stance for the idea of adding type-hints to cfgv's code. Thanks for the nice library!
