### ISSUE TITLE
release tarball (on pypi) does not contain tests

### ISSUE THREAD

**Issue by FelixSchwarz** [asottile/cfgv#23]
It would be nice if the source tarball also contains the tests so these could be run whenever a Fedora package is built.

**Comment by asottile** [comment]
use the github tgz

**Comment by dvzrv** [comment]
Hi! I'm packaging python-cfgv for Arch Linux. I would also like to be able to use the pypi sdist tarball for running tests, as it is more uniquely named, than the github tarballs.
It would be nice if you would reconsider.
