### ISSUE TITLE
cfgv > 3.2.0 regression: cannot handle /dev/fd/?? bash process substitution file on Linux

### ISSUE THREAD

**Issue by vkvm** [asottile/cfgv#72]
PR #50  (released with version `3.3.0` ) causes an issue - cfgv no longer works with the /dev/fd/?? file that bash creates for [process substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html) .

(background context: we have some scripts that use `pre-commit run <(somecript.py)`, where `somescript.py` dynamically generates a pre-commit config ).

The resulting path is something like `/dev/fd/NN`

This eventually gets passed to cfgv.load_from_filename(), resulting in an exception when it fails `os.path.isfile()` here: https://github.com/asottile/cfgv/blob/master/cfgv.py#L395

The previous version used `os.path.exists()`, which worked in this case. It's not clear what the rationale for the change in PR #50 was, but it breaks the ability to handle this case. IMHO, a lower level lib like this should be able to handle this scenario. Can that change be reverted? Or perhaps additional checks on the path are needed to handle multiple possibilities?

**Comment by asottile** [comment]
pre-commit needs a real file to operate correctly in all cases, the change was intentional
